server:
  port: 8080
  servlet:
    # 所有接口都会带上 /api 前缀，例如原接口 /user 会变成 /api/user
    context-path: /admin

spring:
  application:
    name: swagger-ui-spring-boot3-example

swagger-new-ui:
  paths: swagger-new-ui.html,swagger-ui.html,doc.html
  base-url: ${server.servlet.context-path}
